# render.yaml - Configuration pour Render
services:
  - type: web
    name: euria-food-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: mongodb+srv://username:password@cluster.mongodb.net/restaurant_db
      - key: DB_NAME
        value: restaurant_db
      - key: JWT_SECRET
        generateValue: true

  - type: static
    name: euria-food-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./build"
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://euria-food-backend.onrender.com
