[phases.setup]
nixPkgs = ['python311', 'gcc']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'python -m uvicorn server:app --host 0.0.0.0 --port $PORT'
