# Configuration Railway optimisée
[build]
builder = "dockerfile"

[build.buildCommand]
# Force l'utilisation de notre Dockerfile
cmd = ""

[deploy]
startCommand = "python3 -m uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PYTHONPATH = "/app"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
PORT = "8000"

[volumes]
# Aucun volume nécessaire pour ce projet
