[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[variables]
RAILWAY_DOCKERFILE_PATH = "Dockerfile"

[deploy]
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
